const VITE_FIREBASE_API = import.meta.env.VITE_FIREBASE_API;
const VITE_OPENWEATHER_API = import.meta.env.VITE_OPENWEATHER_API;
const VITE_GOOGLE_API = import.meta.env.VITE_GOOGLE_API;
const VITE_GOOGLE_MAP_ID = import.meta.env.VITE_GOOGLE_MAP_ID;

export {
  VITE_FIREBASE_API,
  VITE_OPENWEATHER_API,
  VITE_GOOGLE_API,
  VITE_GOOGLE_MAP_ID,
};
